netpbm depends on libxml2
Fixes compiler error:
gcc-5 -c -I.  -Iimportinc -Iimportinc/netpbm
-I/tmp/netpbm-20190218-123877-kty4hp/converter/other
-I/home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.11/include
-I/home/linuxbrew/.linuxbrew/Cellar/libpng/1.6.36/include/libpng16
-I/tmp/netpbm-20190218-123877-kty4hp/urt -I/usr/include/libxml2
-DNDEBUG       -o rletopnm.o rletopnm.c
gcc-5 -o rletopnm rletopnm.o    -L/tmp/netpbm-20190218-123877-kty4hp/urt
-lrle  -L/tmp/netpbm-20190218-123877-kty4hp/lib -lnetpbm    -lm
gcc-5 -c -I.  -Iimportinc -Iimportinc/netpbm
-I/tmp/netpbm-20190218-123877-kty4hp/converter/other
-I/home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.11/include
-I/home/linuxbrew/.linuxbrew/Cellar/libpng/1.6.36/include/libpng16
-I/tmp/netpbm-20190218-123877-kty4hp/urt -I/usr/include/libxml2
-DNDEBUG       -o pnmtorle.o pnmtorle.c
gcc-5 -o pnmtorle pnmtorle.o    -L/tmp/netpbm-20190218-123877-kty4hp/urt
-lrle  -L/tmp/netpbm-20190218-123877-kty4hp/lib -lnetpbm    -lm
gcc-5 -c -I.  -Iimportinc -Iimportinc/netpbm
-I/tmp/netpbm-20190218-123877-kty4hp/converter/other
-I/home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.11/include
-I/home/linuxbrew/.linuxbrew/Cellar/libpng/1.6.36/include/libpng16
-I/tmp/netpbm-20190218-123877-kty4hp/urt -I/usr/include/libxml2
-DNDEBUG       -o svgtopam.o svgtopam.c
svgtopam.c:36:30: fatal error: libxml/xmlreader.h: No such file or
directory
compilation terminated.
/tmp/netpbm-20190218-123877-kty4hp/common.mk:272: recipe for target
'svgtopam.o' failed
make[2]: *** [svgtopam.o] Error 1
make[2]: Leaving directory
'/tmp/netpbm-20190218-123877-kty4hp/converter/other'
/tmp/netpbm-20190218-123877-kty4hp/common.mk:597: recipe for target
'other/all' failed
make[1]: *** [other/all] Error 2
make[1]: Leaving directory
'/tmp/netpbm-20190218-123877-kty4hp/converter'
/tmp/netpbm-20190218-123877-kty4hp/common.mk:597: recipe for target
'converter/all' failed
make: *** [converter/all] Error 2

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting